# This is a basic workflow to help you get started with Actions

name: CI/CD Asiggment (Thu 28 Jul 2022)

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

  workflow_dispatch:

jobs:
  testing:
    name: Testing (Unit, Integration)
    runs-on: ubuntu-latest
    
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v2
        with:
          node-version: '14'

      - name: Install dependencies
        run: yarn

      - name: Run unit tests
        run: yarn test

  static_code_analysis:
    name: Static code analysis
    runs-on: ubuntu-latest
    # needs: testing


    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v2
        with:
          node-version: '14'
          
      - name: Install dependencies
        run: yarn
        
      - name: Run coverage report
        run: yarn coverage

      - run: yarn add typescript

      - name: SonarQube Scan
        uses: kitabisa/sonarqube-action@v1.2.0
        with:
          host: ${{ secrets.SONARQUBE_HOST }}
          login: ${{ secrets.SONARQUBE_TOKEN }}
          
  dependency_check:
    name: Dependency Check
    runs-on: ubuntu-latest
    # needs: static_code_analysis


    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v2
        with:
          node-version: '14'
          
      - name: Install dependencies
        run: yarn

      - run: npm install -g depcheck

      - name: Dependency Check
        run: npx depcheck

  secret_scan:
    name: Secret scan
    runs-on: ubuntu-latest
    # needs: dependency_check
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0
      - name: Git Leaks scan
        uses: gitleaks/gitleaks-action@v2
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

  license_check:
    name: License check
    runs-on: ubuntu-latest
    # needs: secret_scan

    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-ruby@v1
        with:
          ruby-version: 2.6
      - uses: actions/setup-node@v2
        with:
          node-version: 14
      # install your projects dependencies
      - name: Install dependencies
        run: yarn
      - run: bundle install
      - uses: jonabc/setup-licensed@v1
        with:
         version: 2.x
      - uses: jonabc/licensed-ci@v1
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
      - run: licensed status
      - run: licensed

  security_scan:
    name: Security scan
    runs-on: ubuntu-latest
    # needs: license_check

    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
        with:
          node-version: 14
      # install your projects dependencies
      - name: Install dependencies
        run: yarn

      - name: Start website
        run: |
          yarn run start:development &
          sleep 10

      - name: ZAP Scan
        uses: zaproxy/action-baseline@v0.7.0
        with:
          target: 'http://localhost:3001'
          rules_file_name: '.zap/rules.tsv'
          cmd_options: --autooff

  container_scan:
    name: Container scan
    runs-on: ubuntu-latest
    # needs: security_scan
    env:
      PORT: 3001
      NODE_ENV: "development"
      DOCKLE_HOST: "unix:///var/run/docker.sock"

    steps:
      - uses: actions/checkout@v3

      - name: Build container
        run: docker build --build-arg ENV=$NODE_ENV --build-arg PORT=$PORT --no-cache . -t test_container
        
      - name: Scan container
        uses: Azure/container-scan@v0
        with:
          image-name: test_container:latest
